/*

@title: 
@author: ThePangel
@tags: []
@addedOn: 2024-00-00
*/

const right_note_still = "h";
const left_note_still = "f";
const up_note_still = "t";
const down_note_still = "g";
const right_note = "r";
const left_note = "l";
const up_note = "u";
const down_note = "d";


const song = tune`
750: E4-750,
750: F4-750,
750: G4~750,
750: A4~750,
750: D5~750,
750: D4~750,
750: B4~750,
750: E4~750,
750: A4~750,
750: B4~750,
750: D5~750,
750: C5~750,
750: A4~750,
750: F4~750,
750: A4~750,
750: C5~750,
750: F4~750,
750: D5~750,
750: B4~750,
750: G4~750,
750: E4~750,
750: F4~750,
7500`;

setLegend([right_note, bitmap`
................
................
................
................
........3.......
........33......
.....333333.....
.....3333333....
.....333333.....
........33......
........3.......
................
................
................
................
................`],
  [left_note, bitmap`
................
................
................
................
.......5........
......55........
.....555555.....
....5555555.....
.....555555.....
......55........
.......5........
................
................
................
................
................`],
  [up_note, bitmap`
................
................
................
................
................
.......4........
......444.......
.....44444......
....4444444.....
......444.......
......444.......
......444.......
................
................
................
................`],
  [down_note, bitmap`
................
................
................
................
................
.......HHH......
.......HHH......
.......HHH......
.....HHHHHHH....
......HHHHH.....
.......HHH......
........H.......
................
................
................
................`],
  [right_note_still, bitmap`
................
................
................
.......000......
.......0.00.....
....0000..00....
....0......00...
....0.......0...
....0......00...
....0000..00....
.......0.00.....
.......000......
................
................
................
................`],
  [left_note_still, bitmap`
................
................
................
......000.......
.....00.0.......
....00..0000....
...00......0....
...0.......0....
...00......0....
....00..0000....
.....00.0.......
......000.......
................
................
................
................`],
  [up_note_still, bitmap`
................
................
................
................
......000.......
.....00.00......
....00...00.....
...00.....00....
...0.......0....
...000...000....
.....0...0......
.....0...0......
.....00000......
................
................
................`],
  [down_note_still, bitmap`
................
................
................
................
......00000.....
......0...0.....
......0...0.....
....000...000...
....0.......0...
....00.....00...
.....00...00....
......00.00.....
.......000......
................
................
................`], );


async function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(true)
    }, ms);
  });
}

let level = 0
const levels = [
  map`
ftgh
....
....
....
....
....
....`
]
let score = 0;
let combo = 0;

setMap(levels[level])
split_song = song.split(',');
sprites = [right_note, left_note, up_note, down_note]
tempo = split_song[0].split(':');
tempo = parseInt(tempo[0]);
console.log(tempo);
let isPressed = false
textScore = addText(`${score}`, {
  x: 0,
  y: 2,
  color: color`5`
})
textCombo = addText(`x${combo}`, {
  x: 0,
  y: 4,
  color: color`5`
})

onInput("w", () => {
  
  if (getTile(1, 0).length == 2 && !isPressed) {
    score += 150;
    combo++;
    isPressed = true
    clearText();
    textScore = addText(`${score}`, {
      x: 0,
      y: 2,
      color: color`5`
    })
    textCombo = addText(`x${combo}`, {
      x: 0,
      y: 4,
      color: color`5`
    })
  }


});

onInput("a", () => {
  if (getTile(0, 0).length == 2 && !isPressed) {
    score += 150;
    combo++;
    isPressed = true
    clearText();
    textScore = addText(`${score}`, {
      x: 0,
      y: 2,
      color: color`5`
    })
    textCombo = addText(`x${combo}`, {
      x: 0,
      y: 4,
      color: color`5`
    })
  }

});

onInput("s", () => {
  if (getTile(2, 0).length == 2 && !isPressed) {
    score += 150;
    combo++;
    isPressed = true
    clearText();
    textScore = addText(`${score}`, {
      x: 0,
      y: 2,
      color: color`5`
    })
    textCombo = addText(`x${combo}`, {
      x: 0,
      y: 4,
      color: color`5`
    })
  }

});

onInput("d", () => {
  if (getTile(3, 0).length == 2 && !isPressed) {
    score += 150;
    combo++;
    isPressed = true
    clearText();
    textScore = addText(`${score}`, {
      x: 0,
      y: 2,
      color: color`5`
    })
    textCombo = addText(`x${combo}`, {
      x: 0,
      y: 4,
      color: color`5`
    })
  }

});


async function spawnNote() {

  const randomSprite = sprites[Math.floor(Math.random() * sprites.length)];

  if (randomSprite === left_note) {
    addSprite(0, 6, left_note)
  }
  if (randomSprite === right_note) {
    addSprite(3, 6, right_note)
  }
  if (randomSprite === up_note) {
    addSprite(1, 6, up_note)
  }
  if (randomSprite === down_note) {
    addSprite(2, 6, down_note)
  }


}

async function game() {
  
  setTimeout(() => {
    playTune(song);
  }, 5.5 * tempo);
  for (i = 0; i < split_song.length; i++) {
    console.log("yes" + combo);
    isPressed = false;
    for (j = 0; j < 4; j++) {
      getTile(j, 0).forEach(sprite => {
        if (sprite.type === 'r' || sprite.type === 'l' || sprite.type === 'u' || sprite.type === 'd') {
          sprite.remove(); // Remove the specific sprite
        }
      });

    }
    //console.log(split_song[i]);
    if (/^\d+$/.test(split_song[i].replace("\n", ""))) {

      getAll().forEach(sprite => {
        sprite.y -= 1;
      });

      await sleep(tempo);

    } else {
      spawnNote();
      getAll().forEach(sprite => {
        sprite.y -= 1;
      });

      await sleep(tempo);

    }
    if (!isPressed) {
      combo = 0;
      clearText();
      textCombo = addText(`x${combo}`, {
        x: 0,
        y: 4,
        color: color`5`
      })
    }


  
  }
  time = 0
  while (time <= (5.5 * tempo) - tempo) {
    console.log("no"+combo);
    console.log(time);
    isPressed = false;
    for (j = 0; j < 4; j++) {
      getTile(j, 0).forEach(sprite => {
        if (sprite.type === 'r' || sprite.type === 'l' || sprite.type === 'u' || sprite.type === 'd') {
          sprite.remove(); // Remove the specific sprite
        }
      });

    }
    getAll().forEach(sprite => {
      sprite.y -= 1;
    });
   
    await sleep(tempo);
    
     if (!isPressed && time >= 5.5 * tempo) {
      combo = 0;
      clearText();
       textCombo = addText(`x${combo}`, {
        x: 0,
        y: 4,
        color: color`5`
      })
    }
    time += tempo;
    console.log("noy"+combo);
  }
  



}

game();